title: 秋色柑橘日和
description: 雑記
baseurl: ""
url: ""
logo: /assets/svg/logo.svg
remote_theme: kadopoly/kadopoly.github.io.theme

repository: kadopoly/kadopoly.github.io

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
