title: 秋色柑橘日和
description: theme for kadopoly.github.io
baseurl: ""
url: ""
logo: /assets/svg/logo.svg
#remote_theme: "kadopoly/kadopoly.github.io.theme"
remote_theme: "mmistakes/minimal-mistakes"

github:
  repository_url: https://github.com/kadopoly/kadopoly.github.io

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
